from . struct import Struct
from . bpy_struct import bpy_struct
import mathutils

class ImagePreview(bpy_struct):
    @property
    def rna_type(self):
        '''(Struct) RNA type definition'''
        return Struct()
    @property
    def is_image_custom(self):
        '''(Boolean) True if this preview image has been modified by py
        script,and is no more auto-generated by Blender'''
        return bool()
    @property
    def image_size(self):
        '''(Integer[2]) Width and height in pixels'''
        return int()
    @property
    def image_pixels(self):
        '''(Integer) Image pixels, as bytes (always RGBA 32bits)'''
        return int()
    @property
    def image_pixels_float(self):
        '''(Float) Image pixels components, as floats (RGBA concatenated values)'''
        return float()
    @property
    def is_icon_custom(self):
        '''(Boolean) True if this preview icon has been modified by py script,and
        is no more auto-generated by Blender'''
        return bool()
    @property
    def icon_size(self):
        '''(Integer[2]) Width and height in pixels'''
        return int()
    @property
    def icon_pixels(self):
        '''(Integer) Icon pixels, as bytes (always RGBA 32bits)'''
        return int()
    @property
    def icon_pixels_float(self):
        '''(Float) Icon pixels components, as floats (RGBA concatenated values)'''
        return float()
    @property
    def icon_id(self):
        '''(Integer) Unique integer identifying this preview as an icon (zero
        means invalid)'''
        return int()
    def reload(self):
        '''Reload the preview from its source path'''
        return 